export let data = [
    {
        "Id": 1,
        "Name": "AP Warwick",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Zhonya's Hourglass - Rabadon's Deathcap - Void Staff - Morellonomicon",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.5,
        "description": "AP Warwick in mid lane leverages his strong early game healing and burst damage. Strengths include high sustain and surprising burst potential. Weaknesses are that he can be kited easily and has a weak late game."
    },
    {
        "Id": 2,
        "Name": "Tank Janna",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": "Sunfire Aegis - Ninja Tabi - Thornmail - Spirit Visage - Warmog's Armor - Gargoyle Stoneplate",
        "runes": "Grasp of the Undying - Shield Bash - Second Wind - Revitalize",
        "rating": 3.8,
        "description": "Tank Janna top lane offers unexpected durability and disruptive potential. Strengths include strong disengage and sustain. Weaknesses are low damage output and susceptibility to heavy CC."
    },
    {
        "Id": 3,
        "Name": "AD Thresh",
        "Lane": "ADC",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
        "rating": 4.2,
        "description": "AD Thresh as an ADC offers crowd control with significant burst damage. Strengths include strong dueling potential and pick potential. Weaknesses are his short range and reliance on landing skill shots."
    },
    {
        "Id": 4,
        "Name": "AP Miss Fortune",
        "Lane": "Support",
        "summonerSpell1": "Ignite",
        "summonerSpell2": "Flash",
        "build": "Luden's Echo - Sorcerer's Shoes - Hextech GLP-800 - Liandry's Torment - Zhonya's Hourglass - Morellonomicon",
        "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
        "rating": 4.0,
        "description": "AP Miss Fortune support utilizes her poke and zoning capabilities. Strengths include high poke damage and strong zoning. Weaknesses are lack of CC and being squishy."
    },
    {
        "Id": 5,
        "Name": "Crit Garen",
        "Lane": "Top",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
        "runes": "Conqueror - Triumph - Legend: Tenacity - Last Stand",
        "rating": 3.5,
        "description": "Crit Garen top lane leverages his burst damage and surprising critical hits. Strengths include high burst damage and sustain. Weaknesses are being kited easily and reliance on auto-attacks."
    },
    {
        "Id": 6,
        "Name": "AP Tristana",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Lich Bane",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Relentless Hunter",
        "rating": 4.3,
        "description": "AP Tristana mid lane provides high burst damage and strong all-in potential. Strengths include strong burst and mobility. Weaknesses are short range and being squishy."
    },
    {
        "Id": 7,
        "Name": "Tank Fizz",
        "Lane": "Jungle",
        "summonerSpell1": "Smite",
        "summonerSpell2": "Flash",
        "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
        "runes": "Aftershock - Font of Life - Conditioning - Overgrowth",
        "rating": 3.7,
        "description": "Tank Fizz jungle offers surprising durability and sustain. Strengths include strong engage and sustain. Weaknesses are low damage output and reliance on landing skill shots."
    },
    {
        "Id": 8,
        "Name": "AP Shaco",
        "Lane": "Support",
        "summonerSpell1": "Ignite",
        "summonerSpell2": "Flash",
        "build": "Luden's Echo - Sorcerer's Shoes - Hextech GLP-800 - Morellonomicon - Zhonya's Hourglass - Void Staff",
        "runes": "Dark Harvest - Cheap Shot - Eyeball Collection - Ultimate Hunter",
        "rating": 4.1,
        "description": "AP Shaco support uses his clone and boxes to disrupt and deal significant burst damage. Strengths include high burst damage and deception. Weaknesses are being squishy and reliant on clone mechanics."
    },
    {
        "Id": 9,
        "Name": "AD Sona",
        "Lane": "ADC",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
        "rating": 3.9,
        "description": "AD Sona ADC offers consistent damage output and self-healing. Strengths include strong sustain and consistent damage. Weaknesses are being squishy and having low mobility."
    },
    {
        "Id": 10,
        "Name": "AP Malphite",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Zhonya's Hourglass - Rabadon's Deathcap - Void Staff - Morellonomicon",
        "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
        "rating": 4.6,
        "description": "AP Malphite mid lane brings strong burst damage and engage potential. Strengths include high burst damage and strong engage. Weaknesses are being mana reliant and having a weak early game."
    },
    {
        "Id": 11,
        "Name": "Crit Leona",
        "Lane": "Top",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
        "runes": "Press the Attack - Triumph - Legend: Bloodline - Coup de Grace",
        "rating": 3.4,
        "description": "Crit Leona top lane leverages her burst damage and crowd control. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and having low sustained damage."
    },
    {
        "Id": 12,
        "Name": "AD Ahri",
        "Lane": "ADC",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
        "rating": 4.0,
        "description": "AD Ahri ADC offers mobility and strong pick potential. Strengths include high mobility and pick potential. Weaknesses are being squishy and reliant on landing skill shots."
    },
    {
        "Id": 13,
        "Name": "AP Ezreal",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Lich Bane",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.1,
        "description": "AP Ezreal mid lane provides high poke damage and mobility. Strengths include high poke damage and mobility. Weaknesses are being squishy and mana reliant."
    },
    {
        "Id": 14,
        "Name": "Tank Master Yi",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": "Sunfire Aegis - Ninja Tabi - Spirit Visage - Thornmail - Randuin's Omen - Sterak's Gage",
        "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
        "rating": 3.6,
        "description": "Tank Master Yi top lane provides durability and sustain. Strengths include high sustain and dueling potential. Weaknesses are low damage output and being kited easily."
    },
    {
        "Id": 15,
        "Name": "AP Twitch",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Dark Harvest - Cheap Shot - Eyeball Collection - Ravenous Hunter",
        "rating": 4.4,
        "description": "AP Twitch mid lane leverages his high burst damage and stealth. Strengths include high burst damage and stealth potential. Weaknesses are being squishy and reliant on positioning."
    },
    {
        "Id": 16,
        "Name": "AD Soraka",
        "Lane": "ADC",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
        "rating": 3.8,
        "description": "AD Soraka ADC offers consistent damage and self-sustain. Strengths include high sustain and consistent damage. Weaknesses are being squishy and low mobility."
    },
    {
        "Id": 17,
        "Name": "AP Nasus",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
        "rating": 4.2,
        "description": "AP Nasus mid lane provides high burst damage and strong poke. Strengths include high burst damage and poke. Weaknesses are being mana reliant and having a weak early game."
    },
    {
        "Id": 18,
        "Name": "Tank Zilean",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
        "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
        "rating": 3.5,
        "description": "Tank Zilean top lane provides strong utility and durability. Strengths include strong utility and sustain. Weaknesses are low damage output and being mana reliant."
    },
    {
        "Id": 19,
        "Name": "AD Morgana",
        "Lane": "ADC",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
        "rating": 3.7,
        "description": "AD Morgana ADC offers consistent damage and utility. Strengths include strong utility and consistent damage. Weaknesses are being squishy and low mobility."
    },
    {
        "Id": 20,
        "Name": "AP Rengar",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.3,
        "description": "AP Rengar mid lane leverages his high burst damage and mobility. Strengths include high burst damage and mobility. Weaknesses are being squishy and reliant on landing skill shots."
    },
    {
        "Id": 21,
        "Name": "Crit Blitzcrank",
        "Lane": "Top",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
        "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
        "rating": 3.6,
        "description": "Crit Blitzcrank top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
    },
    {
        "Id": 22,
        "Name": "AP Pyke",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.1,
        "description": "AP Pyke mid lane leverages his high burst damage and stealth. Strengths include high burst damage and stealth potential. Weaknesses are being squishy and reliant on positioning."
    },
    {
        "Id": 23,
        "Name": "AD Malzahar",
        "Lane": "ADC",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
        "rating": 3.9,
        "description": "AD Malzahar ADC offers consistent damage and utility. Strengths include strong utility and consistent damage. Weaknesses are being squishy and low mobility."
    },
    {
        "Id": 24,
        "Name": "AP Kled",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.2,
        "description": "AP Kled mid lane provides high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being squishy and reliant on landing skill shots."
    },
    {
        "Id": 25,
        "Name": "Tank Akali",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
        "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
        "rating": 3.4,
        "description": "Tank Akali top lane provides durability and sustain. Strengths include high sustain and dueling potential. Weaknesses are low damage output and being kited easily."
    },
    {
        "Id": 26,
        "Name": "AP Darius",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.0,
        "description": "AP Darius mid lane leverages his high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being squishy and reliant on landing skill shots."
    },
    {
        "Id": 27,
        "Name": "Crit Galio",
        "Lane": "Top",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
        "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
        "rating": 3.5,
        "description": "Crit Galio top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
    },
    {
        "Id": 28,
        "Name": "AP Dr. Mundo",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.1,
        "description": "AP Dr. Mundo mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on landing skill shots."
    },
    {
        "Id": 29,
        "Name": "AD Sion",
        "Lane": "ADC",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
        "rating": 3.8,
        "description": "AD Sion ADC offers consistent damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
    },
    {
        "Id": 30,
        "Name": "Tank Talon",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
        "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
        "rating": 3.6,
        "description": "Tank Talon top lane provides durability and sustain. Strengths include high sustain and dueling potential. Weaknesses are low damage output and being kited easily."
    },
    {
        "Id": 31,
        "Name": "AP Nocturne",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.0,
        "description": "AP Nocturne mid lane leverages his high burst damage and mobility. Strengths include high burst damage and mobility. Weaknesses are being squishy and reliant on landing skill shots."
    },
    {
        "Id": 32,
        "Name": "Crit Rammus",
        "Lane": "Top",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
        "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
        "rating": 3.7,
        "description": "Crit Rammus top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
    },
    {
        "Id": 33,
        "Name": "AP Skarner",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.1,
        "description": "AP Skarner mid lane leverages his high burst damage and mobility. Strengths include high burst damage and mobility. Weaknesses are being squishy and reliant on landing skill shots."
    },
    {
        "Id": 34,
        "Name": "AD Swain",
        "Lane": "ADC",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
        "rating": 3.8,
        "description": "AD Swain ADC offers consistent damage and sustain. Strengths include high sustain and consistent damage. Weaknesses are being squishy and low mobility."
    },
    {
        "Id": 35,
        "Name": "Tank Veigar",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
        "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
        "rating": 3.6,
        "description": "Tank Veigar top lane provides durability and strong crowd control. Strengths include strong crowd control and durability. Weaknesses are low damage output and being mana reliant."
    },
    {
        "Id": 36,
        "Name": "AP Urgot",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
        "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
        "rating": 4.0,
        "description": "AP Urgot mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on landing skill shots."
    },
    {
        "Id": 37,
        "Name": "Crit Zac",
        "Lane": "Top",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
        "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
        "rating": 3.5,
        "description": "Crit Zac top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
    },
        {
            "Id": 38,
            "Name": "AP Shen",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.1,
            "description": "AP Shen mid lane offers surprising burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
        },
        {
            "Id": 39,
            "Name": "AD Sona",
            "Lane": "ADC",
            "summonerSpell1": "Heal",
            "summonerSpell2": "Flash",
            "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
            "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
            "rating": 3.7,
            "description": "AD Sona ADC offers consistent damage and utility. Strengths include strong utility and consistent damage. Weaknesses are being squishy and low mobility."
        },
        {
            "Id": 40,
            "Name": "AP Thresh",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.0,
            "description": "AP Thresh mid lane leverages his burst damage and crowd control. Strengths include high burst damage and crowd control. Weaknesses are being squishy and reliant on landing skill shots."
        },
        {
            "Id": 41,
            "Name": "Crit Gragas",
            "Lane": "Top",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
            "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
            "rating": 3.5,
            "description": "Crit Gragas top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
        },
        {
            "Id": 42,
            "Name": "AP Illaoi",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.2,
            "description": "AP Illaoi mid lane leverages her high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on landing skill shots."
        },
        {
            "Id": 43,
            "Name": "AD Lux",
            "Lane": "ADC",
            "summonerSpell1": "Heal",
            "summonerSpell2": "Flash",
            "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
            "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
            "rating": 3.8,
            "description": "AD Lux ADC offers consistent damage and strong poke. Strengths include high poke damage and consistent damage. Weaknesses are being squishy and reliant on skill shots."
        },
        {
            "Id": 44,
            "Name": "Tank Vayne",
            "Lane": "Top",
            "summonerSpell1": "Teleport",
            "summonerSpell2": "Flash",
            "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
            "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
            "rating": 3.6,
            "description": "Tank Vayne top lane provides durability and sustain. Strengths include high sustain and dueling potential. Weaknesses are low damage output and being kited easily."
        },
        {
            "Id": 45,
            "Name": "AP Renekton",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.1,
            "description": "AP Renekton mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
        },
        {
            "Id": 46,
            "Name": "Crit Taric",
            "Lane": "Top",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
            "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
            "rating": 3.7,
            "description": "Crit Taric top lane offers high burst damage and strong sustain. Strengths include high burst damage and sustain. Weaknesses are being kited easily and low sustained damage."
        },
        {
            "Id": 47,
            "Name": "AD Zyra",
            "Lane": "ADC",
            "summonerSpell1": "Heal",
            "summonerSpell2": "Flash",
            "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
            "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
            "rating": 3.8,
            "description": "AD Zyra ADC offers consistent damage and strong poke. Strengths include high poke damage and consistent damage. Weaknesses are being squishy and reliant on skill shots."
        },
        {
            "Id": 48,
            "Name": "AP Olaf",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.2,
            "description": "AP Olaf mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
        },
        {
            "Id": 49,
            "Name": "Tank Fizz",
            "Lane": "Top",
            "summonerSpell1": "Teleport",
            "summonerSpell2": "Flash",
            "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
            "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
            "rating": 3.5,
            "description": "Tank Fizz top lane provides durability and sustain. Strengths include high sustain and dueling potential. Weaknesses are low damage output and being kited easily."
        },
        {
            "Id": 50,
            "Name": "AP Jax",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.1,
            "description": "AP Jax mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
        },
        {
            "Id": 51,
            "Name": "Crit Singed",
            "Lane": "Top",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
            "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
            "rating": 3.6,
            "description": "Crit Singed top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
        },
        {
            "Id": 52,
            "Name": "AP Tryndamere",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.0,
            "description": "AP Tryndamere mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
        },
        {
            "Id": 53,
            "Name": "Tank Yasuo",
            "Lane": "Top",
            "summonerSpell1": "Teleport",
            "summonerSpell2": "Flash",
            "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
            "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
            "rating": 3.7,
            "description": "Tank Yasuo top lane provides durability and sustain. Strengths include high sustain and dueling potential. Weaknesses are low damage output and being kited easily."
        },
        {
            "Id": 54,
            "Name": "AP Aatrox",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.1,
            "description": "AP Aatrox mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
        },
        {
            "Id": 55,
            "Name": "Crit Ornn",
            "Lane": "Top",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
            "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
            "rating": 3.7,
            "description": "Crit Ornn top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
        },
        {
            "Id": 56,
            "Name": "AD Morgana",
            "Lane": "ADC",
            "summonerSpell1": "Heal",
            "summonerSpell2": "Flash",
            "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
            "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
            "rating": 3.8,
            "description": "AD Morgana ADC offers consistent damage and strong poke. Strengths include high poke damage and consistent damage. Weaknesses are being squishy and reliant on skill shots."
        },
        {
            "Id": 57,
            "Name": "Tank Zed",
            "Lane": "Top",
            "summonerSpell1": "Teleport",
            "summonerSpell2": "Flash",
            "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
            "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
            "rating": 3.6,
            "description": "Tank Zed top lane provides durability and sustain. Strengths include high sustain and dueling potential. Weaknesses are low damage output and being kited easily."
        },
        {
            "Id": 58,
            "Name": "AP Rengar",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.2,
            "description": "AP Rengar mid lane leverages his high burst damage and mobility. Strengths include high burst damage and mobility. Weaknesses are being squishy and reliant on landing skill shots."
        },
        {
            "Id": 59,
            "Name": "Crit Malphite",
            "Lane": "Top",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
            "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
            "rating": 3.7,
            "description": "Crit Malphite top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
        },
        {
            "Id": 60,
            "Name": "AP Kayle",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.1,
            "description": "AP Kayle mid lane leverages her high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
        },
        {
            "Id": 61,
            "Name": "Tank Zilean",
            "Lane": "Top",
            "summonerSpell1": "Teleport",
            "summonerSpell2": "Flash",
            "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
            "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
            "rating": 3.6,
            "description": "Tank Zilean top lane provides durability and strong utility. Strengths include strong utility and durability. Weaknesses are low damage output and being mana reliant."
        },
        {
            "Id": 62,
            "Name": "AP Trundle",
            "Lane": "Mid",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
            "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
            "rating": 4.0,
            "description": "AP Trundle mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
        },
        {
            "Id": 63,
            "Name": "Crit Braum",
            "Lane": "Top",
            "summonerSpell1": "Flash",
            "summonerSpell2": "Ignite",
            "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
            "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
            "rating": 3.5,
            "description": "Crit Braum top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
        },
    {
    "Id": 64,
    "Name": "AP Mordekaiser",
    "Lane": "Mid",
    "summonerSpell1": "Flash",
    "summonerSpell2": "Ignite",
    "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
    "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
    "rating": 4.2,
    "description": "AP Mordekaiser mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
},
{
    "Id": 65,
    "Name": "AD Maokai",
    "Lane": "ADC",
    "summonerSpell1": "Heal",
    "summonerSpell2": "Flash",
    "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
    "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
    "rating": 3.8,
    "description": "AD Maokai ADC offers consistent damage and strong crowd control. Strengths include strong crowd control and consistent damage. Weaknesses are being squishy and reliant on cooldowns."
},
{
    "Id": 66,
    "Name": "AP Wukong",
    "Lane": "Mid",
    "summonerSpell1": "Flash",
    "summonerSpell2": "Ignite",
    "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
    "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
    "rating": 4.0,
    "description": "AP Wukong mid lane leverages his high burst damage and crowd control. Strengths include high burst damage and crowd control. Weaknesses are being squishy and reliant on cooldowns."
},
{
    "Id": 67,
    "Name": "Crit Diana",
    "Lane": "Top",
    "summonerSpell1": "Flash",
    "summonerSpell2": "Ignite",
    "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
    "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
    "rating": 3.7,
    "description": "Crit Diana top lane offers high burst damage and strong engage. Strengths include high burst damage and strong engage. Weaknesses are being kited easily and low sustained damage."
},
{
    "Id": 68,
    "Name": "AP Nautilus",
    "Lane": "Mid",
    "summonerSpell1": "Flash",
    "summonerSpell2": "Ignite",
    "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
    "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
    "rating": 4.1,
    "description": "AP Nautilus mid lane leverages his high burst damage and crowd control. Strengths include high burst damage and crowd control. Weaknesses are being squishy and reliant on cooldowns."
},
{
    "Id": 69,
    "Name": "Tank Yorick",
    "Lane": "Top",
    "summonerSpell1": "Teleport",
    "summonerSpell2": "Flash",
    "build": "Sunfire Aegis - Mercury's Treads - Spirit Visage - Abyssal Mask - Thornmail - Warmog's Armor",
    "runes": "Grasp of the Undying - Demolish - Conditioning - Overgrowth",
    "rating": 3.6,
    "description": "Tank Yorick top lane provides durability and strong split-pushing potential. Strengths include strong split-pushing and durability. Weaknesses are low mobility and being easily kited."
},
{
    "Id": 70,
    "Name": "AP Volibear",
    "Lane": "Mid",
    "summonerSpell1": "Flash",
    "summonerSpell2": "Ignite",
    "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
    "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
    "rating": 4.0,
    "description": "AP Volibear mid lane leverages his high burst damage and sustain. Strengths include high burst damage and sustain. Weaknesses are being squishy and reliant on cooldowns."
},
{
    "Id": 71,
    "Name": "Crit Teemo",
    "Lane": "Top",
    "summonerSpell1": "Flash",
    "summonerSpell2": "Ignite",
    "build": "Infinity Edge - Berserker's Greaves - Phantom Dancer - Essence Reaver - Statikk Shiv - Mortal Reminder",
    "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
    "rating": 3.7,
    "description": "Crit Teemo top lane offers high burst damage and strong poke. Strengths include high poke damage and strong burst. Weaknesses are being squishy and reliant on skill shots."
},
{
    "Id": 72,
    "Name": "AP Riven",
    "Lane": "Mid",
    "summonerSpell1": "Flash",
    "summonerSpell2": "Ignite",
    "build": "Luden's Echo - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
    "runes": "Electrocute - Taste of Blood - Eyeball Collection - Ravenous Hunter",
    "rating": 4.2,
    "description": "AP Riven mid lane leverages her high burst damage and mobility. Strengths include high burst damage and mobility. Weaknesses are being squishy and reliant on landing skill shots."
},
    {
    "Id": 73,
    "Name": "AD Leona",
    "Lane": "ADC",
    "summonerSpell1": "Heal",
    "summonerSpell2": "Flash",
    "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
    "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
    "rating": 3.8,
    "description": "AD Leona ADC offers high kill pressure and crowd control. Strengths include strong engage and crowd control. Weaknesses are being reliant on cooldowns and lack of mobility."
},
{
    "Id": 74,
    "Name": "AP Ashe",
    "Lane": "Support",
    "summonerSpell1": "Exhaust",
    "summonerSpell2": "Flash",
    "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
    "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
    "rating": 4.0,
    "description": "AP Ashe support brings strong poke and utility to the bot lane. Strengths include long-range poke and utility. Weaknesses are being squishy and reliant on landing skill shots."
},
{
    "Id": 75,
    "Name": "AD Fiddlesticks",
    "Lane": "ADC",
    "summonerSpell1": "Heal",
    "summonerSpell2": "Flash",
    "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
    "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
    "rating": 3.7,
    "description": "AD Fiddlesticks ADC offers surprising sustain and crowd control. Strengths include strong poke and crowd control. Weaknesses are being squishy and reliant on skill shots."
},
{
    "Id": 76,
    "Name": "AP Thresh",
    "Lane": "Support",
    "summonerSpell1": "Exhaust",
    "summonerSpell2": "Flash",
    "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
    "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
    "rating": 4.1,
    "description": "AP Thresh support brings unexpected burst and crowd control to the bot lane. Strengths include strong engage and crowd control. Weaknesses are being squishy and reliant on landing skill shots."
},
{
    "Id": 77,
    "Name": "AD Morgana",
    "Lane": "ADC",
    "summonerSpell1": "Heal",
    "summonerSpell2": "Flash",
    "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
    "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
    "rating": 3.8,
    "description": "AD Morgana ADC offers consistent damage and strong poke. Strengths include high poke damage and consistent damage. Weaknesses are being squishy and reliant on skill shots."
},
{
    "Id": 78,
    "Name": "AP Bard",
    "Lane": "Support",
    "summonerSpell1": "Exhaust",
    "summonerSpell2": "Flash",
    "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
    "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
    "rating": 4.0,
    "description": "AP Bard support provides strong roaming potential and utility. Strengths include roaming potential and crowd control. Weaknesses are being squishy and reliant on skill shots."
},
{
    "Id": 79,
    "Name": "AD Lulu",
    "Lane": "ADC",
    "summonerSpell1": "Heal",
    "summonerSpell2": "Flash",
    "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
    "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
    "rating": 3.7,
    "description": "AD Lulu ADC offers surprising damage and strong utility. Strengths include strong utility and poke. Weaknesses are being squishy and reliant on cooldowns."
},
{
    "Id": 80,
    "Name": "AP Senna",
    "Lane": "Support",
    "summonerSpell1": "Exhaust",
    "summonerSpell2": "Flash",
    "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
    "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
    "rating": 4.1,
    "description": "AP Senna support offers strong poke and healing. Strengths include long-range poke and utility. Weaknesses are being squishy and reliant on landing skill shots."
},
{
    "Id": 81,
    "Name": "AD Zilean",
    "Lane": "ADC",
    "summonerSpell1": "Heal",
    "summonerSpell2": "Flash",
    "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
    "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
    "rating": 3.8,
    "description": "AD Zilean ADC offers surprising burst and utility. Strengths include strong utility and surprising burst. Weaknesses are being reliant on cooldowns and lack of mobility."
},
    {
        "Id": 82,
        "Name": "AP Taric",
        "Lane": "Support",
        "summonerSpell1": "Exhaust",
        "summonerSpell2": "Flash",
        "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
        "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
        "rating": 4.0,
        "description": "AP Taric support offers strong sustain and crowd control."
    },
        {
            "Id": 83,
            "Name": "AP Ezreal",
            "Lane": "ADC",
            "summonerSpell1": "Heal",
            "summonerSpell2": "Flash",
            "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
            "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
            "rating": 4.2,
            "description": "AP Ezreal ADC brings high poke damage and burst potential. Strengths include long-range poke and burst. Weaknesses are being mana reliant and squishy."
        },
            {
                "Id": 84,
                "Name": "AD Kennen",
                "Lane": "ADC",
                "summonerSpell1": "Heal",
                "summonerSpell2": "Flash",
                "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
                "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
                "rating": 4.1,
                "description": "AD Kennen ADC offers strong poke and crowd control. Strengths include strong poke and crowd control. Weaknesses are being reliant on skill shots and squishy."
            },
            {
                "Id": 85,
                "Name": "AP Kog'Maw",
                "Lane": "ADC",
                "summonerSpell1": "Heal",
                "summonerSpell2": "Flash",
                "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
                "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
                "rating": 4.0,
                "description": "AP Kog'Maw ADC brings high poke damage and scaling. Strengths include long-range poke and scaling damage. Weaknesses are being immobile and reliant on positioning."
            },
            {
                "Id": 86,
                "Name": "AD Malzahar",
                "Lane": "ADC",
                "summonerSpell1": "Heal",
                "summonerSpell2": "Flash",
                "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
                "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
                "rating": 4.0,
                "description": "AD Malzahar ADC provides strong pushing power and single-target damage. Strengths include strong pushing power and single-target damage. Weaknesses are being immobile and reliant on voidlings."
            },
            {
                "Id": 87,
                "Name": "AP Lucian",
                "Lane": "ADC",
                "summonerSpell1": "Heal",
                "summonerSpell2": "Flash",
                "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
                "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
                "rating": 4.1,
                "description": "AP Lucian ADC offers high burst damage and mobility. Strengths include high burst damage and mobility. Weaknesses are being mana reliant and squishy."
            },
            {
                "Id": 88,
                "Name": "AD Twisted Fate",
                "Lane": "ADC",
                "summonerSpell1": "Heal",
                "summonerSpell2": "Flash",
                "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
                "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
                "rating": 4.0,
                "description": "AD Twisted Fate ADC brings strong map pressure and burst. Strengths include strong map pressure and burst. Weaknesses are being squishy and reliant on cooldowns."
            },
            {
                "Id": 89,
                "Name": "AP Vayne",
                "Lane": "ADC",
                "summonerSpell1": "Heal",
                "summonerSpell2": "Flash",
                "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
                "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
                "rating": 4.1,
                "description": "AP Vayne ADC offers surprising burst and mobility. Strengths include surprising burst and mobility. Weaknesses are being short-ranged and reliant on cooldowns."
            },
            {
                "Id": 90,
                "Name": "AD Syndra",
                "Lane": "ADC",
                "summonerSpell1": "Heal",
                "summonerSpell2": "Flash",
                "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
                "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
                "rating": 4.0,
                "description": "AD Syndra ADC provides strong lane harassment and burst. Strengths include strong lane harassment and burst. Weaknesses are being mana reliant and squishy."
            },
                {
                    "Id": 91,
                    "Name": "AP Varus",
                    "Lane": "ADC",
                    "summonerSpell1": "Heal",
                    "summonerSpell2": "Flash",
                    "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
                    "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
                    "rating": 4.2,
                    "description": "AP Varus ADC brings strong poke and crowd control. Strengths include long-range poke and crowd control. Weaknesses are being mana reliant and squishy."
                },
                    {
                        "Id": 92,
                        "Name": "AD Taliyah",
                        "Lane": "ADC",
                        "summonerSpell1": "Heal",
                        "summonerSpell2": "Flash",
                        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
                        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
                        "rating": 4.1,
                        "description": "AD Taliyah ADC offers surprising burst and crowd control. Strengths include surprising burst and crowd control. Weaknesses are being reliant on skill shots and squishy."
                    },
                    {
                        "Id": 93,
                        "Name": "AP Quinn",
                        "Lane": "ADC",
                        "summonerSpell1": "Heal",
                        "summonerSpell2": "Flash",
                        "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
                        "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
                        "rating": 4.0,
                        "description": "AP Quinn ADC provides strong roaming potential and burst. Strengths include strong roaming potential and burst. Weaknesses are being short-ranged and squishy."
                    },
                    {
                        "Id": 94,
                        "Name": "AD Ziggs",
                        "Lane": "ADC",
                        "summonerSpell1": "Heal",
                        "summonerSpell2": "Flash",
                        "build": "Kraken Slayer - Berserker's Greaves - Infinity Edge - Phantom Dancer - The Collector - Guardian Angel",
                        "runes": "Press the Attack - Overheal - Legend: Alacrity - Coup de Grace",
                        "rating": 4.0,
                        "description": "AD Ziggs ADC brings strong poke and wave clear. Strengths include strong poke and wave clear. Weaknesses are being reliant on skill shots and squishy."
                    },
                    {
                        "Id": 95,
                        "Name": "AP Sivir",
                        "Lane": "ADC",
                        "summonerSpell1": "Heal",
                        "summonerSpell2": "Flash",
                        "build": "Luden's Tempest - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Morellonomicon - Void Staff",
                        "runes": "Arcane Comet - Manaflow Band - Transcendence - Scorch",
                        "rating": 4.1,
                        "description": "AP Sivir ADC offers strong wave clear and poke. Strengths include strong wave clear and poke. Weaknesses are being reliant on mana and squishy."
                    },
                        {
                            "Id": 96,
                            "Name": "AP Jarvan IV",
                            "Lane": "Jungle",
                            "summonerSpell1": "Smite",
                            "summonerSpell2": "Flash",
                            "build": "Hextech Rocketbelt - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
                            "runes": "Dark Harvest - Cheap Shot - Eyeball Collection - Ultimate Hunter",
                            "rating": 4.2,
                            "description": "AP Jarvan IV jungle provides strong burst damage and engage. Strengths include strong burst damage and engage. Weaknesses are being squishy and reliant on cooldowns."
                        },
                            {
                                "Id": 97,
                                "Name": "AD Malphite",
                                "Lane": "Jungle",
                                "summonerSpell1": "Smite",
                                "summonerSpell2": "Flash",
                                "build": "Divine Sunderer - Plated Steelcaps - Black Cleaver - Sterak's Gage - Thornmail - Spirit Visage",
                                "runes": "Conqueror - Triumph - Legend: Tenacity - Last Stand",
                                "rating": 4.1,
                                "description": "AD Malphite jungle offers strong engage and tankiness. Strengths include strong engage and tankiness. Weaknesses are being mana reliant and lacking early game damage."
                            },
                            {
                                "Id": 98,
                                "Name": "AP Vi",
                                "Lane": "Jungle",
                                "summonerSpell1": "Smite",
                                "summonerSpell2": "Flash",
                                "build": "Hextech Rocketbelt - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
                                "runes": "Dark Harvest - Cheap Shot - Eyeball Collection - Ultimate Hunter",
                                "rating": 4.0,
                                "description": "AP Vi jungle brings unexpected burst and crowd control. Strengths include unexpected burst and crowd control. Weaknesses are being squishy and reliant on cooldowns."
                            },
                            {
                                "Id": 99,
                                "Name": "AD Rumble",
                                "Lane": "Jungle",
                                "summonerSpell1": "Smite",
                                "summonerSpell2": "Flash",
                                "build": "Kraken Slayer - Plated Steelcaps - Infinity Edge - Phantom Dancer - Guardian Angel - Mortal Reminder",
                                "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
                                "rating": 3.8,
                                "description": "AD Rumble jungle offers surprising damage and tankiness. Strengths include surprising damage and tankiness. Weaknesses are being reliant on cooldowns and lacking mobility."
                            },
                            {
                                "Id": 100,
                                "Name": "AP Shyvana",
                                "Lane": "Jungle",
                                "summonerSpell1": "Smite",
                                "summonerSpell2": "Flash",
                                "build": "Hextech Rocketbelt - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
                                "runes": "Dark Harvest - Cheap Shot - Eyeball Collection - Ultimate Hunter",
                                "rating": 4.0,
                                "description": "AP Shyvana jungle offers unexpected burst and tankiness. Strengths include unexpected burst and tankiness. Weaknesses are being reliant on cooldowns and lacking early game damage."
                            },
                            {
                                "Id": 101,
                                "Name": "AD Maokai",
                                "Lane": "Jungle",
                                "summonerSpell1": "Smite",
                                "summonerSpell2": "Flash",
                                "build": "Kraken Slayer - Plated Steelcaps - Infinity Edge - Phantom Dancer - Guardian Angel - Mortal Reminder",
                                "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
                                "rating": 3.7,
                                "description": "AD Maokai jungle offers surprising damage and crowd control. Strengths include surprising damage and crowd control. Weaknesses are being reliant on cooldowns and lacking mobility."
                            },
                            {
                                "Id": 102,
                                "Name": "AP Twitch",
                                "Lane": "Jungle",
                                "summonerSpell1": "Smite",
                                "summonerSpell2": "Flash",
                                "build": "Hextech Rocketbelt - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
                                "runes": "Dark Harvest - Cheap Shot - Eyeball Collection - Ultimate Hunter",
                                "rating": 4.1,
                                "description": "AP Twitch jungle offers unexpected burst and crowd control. Strengths include unexpected burst and crowd control. Weaknesses are being squishy and reliant on stealth."
                            },
                            {
                                "Id": 103,
                                "Name": "AD Nocturne",
                                "Lane": "Jungle",
                                "summonerSpell1": "Smite",
                                "summonerSpell2": "Flash",
                                "build": "Kraken Slayer - Plated Steelcaps - Infinity Edge - Phantom Dancer - Guardian Angel - Mortal Reminder",
                                "runes": "Press the Attack - Triumph - Legend: Alacrity - Coup de Grace",
                                "rating": 3.8,
                                "description": "AD Nocturne jungle offers strong dueling and burst. Strengths include strong dueling and burst. Weaknesses are being reliant on cooldowns and lacking early game presence."
                            },
                            {
                                "Id": 104,
                                "Name": "AP Rek'Sai",
                                "Lane": "Jungle",
                                "summonerSpell1": "Smite",
                                "summonerSpell2": "Flash",
                                "build": "Hextech Rocketbelt - Sorcerer's Shoes - Rabadon's Deathcap - Zhonya's Hourglass - Void Staff - Morellonomicon",
                                "runes": "Dark Harvest - Cheap Shot - Eyeball Collection - Ultimate Hunter",
                                "rating": 4.0,
                                "description": "AP Rek'Sai jungle provides strong engage and burst. Strengths include strong engage and burst. Weaknesses are being squishy and reliant on cooldowns."
                            },
    {
        "Id": 105,
        "Name": "AD Hecarim",
        "Lane": "Jungle",
        "summonerSpell1": "Smite",
        "summonerSpell2": "Flash",
        "build": "Divine Sunderer - Plated Steelcaps - Black Cleaver - Sterak's Gage - Thornmail - Spirit Visage",
        "runes": "Conqueror - Triumph - Legend: Tenacity - Last Stand",
        "rating": 4.1,
        "description": "AD Hecarim jungle offers strong early game presence and mobility. Strengths include strong early game."
    }
]

