export let data = [ {
    Id: 1,
    Name: "AP Warwick",
    Lane: "Mid",
    summonerSpell1: "Flash",
    summonerSpell2: "Ignite",
    build: " ",
    runes: " ",
    rating: 4.5,
    description: "AP Warwick in mid lane leverages his strong early game healing and burst damage. Strengths include high sustain and surprising burst potential. Weaknesses are that he can be kited easily and has a weak late game."
},
    {
        Id: 2,
        Name: "Crit Malphite",
        Lane: "Top",
        summonerSpell1: "Flash",
        summonerSpell2: "Teleport",
        build: " ",
        runes: " ",
        rating: 4.0,
        description: "Crit Malphite focuses on maximizing his AD scaling abilities to burst down squishy targets. Strengths include massive burst damage with his ultimate. Weaknesses are lack of sustained damage and being very item-dependent."
    },
    {
        Id: 3,
        Name: "Tank Ekko",
        Lane: "Jungle",
        summonerSpell1: "Smite",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 3.8,
        description: "Tank Ekko sacrifices some of his burst for incredible survivability, allowing him to disrupt team fights and peel for carries. Strengths include high survivability and good crowd control. Weaknesses are lower damage output and slower clear times."
    },
    {
        Id: 4,
        Name: "AD Neeko",
        Lane: "Bot",
        summonerSpell1: "Heal",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 4.2,
        description: "AD Neeko in the bot lane uses her auto-attacks and on-hit effects to deal damage. Strengths include high burst potential with her ultimate and deceptive playmaking. Weaknesses are shorter range and reliance on abilities to deal damage."
    },
    {
        Id: 5,
        Name: "AP Shaco Support",
        Lane: "Support",
        summonerSpell1: "Ignite",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 4.7,
        description: "AP Shaco support focuses on using his boxes and deception to control the lane. Strengths include strong lane control and high burst potential. Weaknesses are being squishy and reliant on snowballing early."
    },
    {
        Id: 6,
        Name: "AD Thresh",
        Lane: "Top",
        summonerSpell1: "Flash",
        summonerSpell2: "Ignite",
        build: " ",
        runes: " ",
        rating: 4.1,
        description: "AD Thresh top relies on his basic attacks and AD scaling abilities to deal damage. Strengths include surprising burst damage and strong crowd control. Weaknesses are a lack of mobility and being item-reliant."
    },
    {
        Id: 7,
        Name: "AP Tristana",
        Lane: "Mid",
        summonerSpell1: "Flash",
        summonerSpell2: "Ignite",
        build: " ",
        runes: " ",
        rating: 4.3,
        description: "AP Tristana mid focuses on her ability power scaling to burst down enemies. Strengths include strong burst and high mobility. Weaknesses are that she can be vulnerable to all-ins and has a weak early game."
    },
    {
        Id: 8,
        Name: "Tank Katarina",
        Lane: "Top",
        summonerSpell1: "Flash",
        summonerSpell2: "Teleport",
        build: " ",
        runes: " ",
        rating: 3.9,
        description: "Tank Katarina sacrifices damage for survivability, making her a disruptive force in team fights. Strengths include high survivability and mobility. Weaknesses are lower damage output and reliance on resets."
    },
    {
        Id: 9,
        Name: "Full AP Malphite",
        Lane: "Mid",
        summonerSpell1: "Flash",
        summonerSpell2: "Ignite",
        build: " ",
        runes: " ",
        rating: 4.6,
        description: "Full AP Malphite mid focuses on bursting down enemies with his ultimate. Strengths include massive burst damage and strong engage. Weaknesses are that he is very cooldown-reliant and can be kited."
    },
    {
        Id: 10,
        Name: "AD Kennen",
        Lane: "Bot",
        summonerSpell1: "Heal",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 4.0,
        description: "AD Kennen bot leverages his attack speed and on-hit effects. Strengths include high sustained damage and strong crowd control. Weaknesses are being squishy and having shorter range."
    },
    {
        Id: 11,
        Name: "AP Nasus",
        Lane: "Mid",
        summonerSpell1: "Flash",
        summonerSpell2: "Teleport",
        build: " ",
        runes: " ",
        rating: 4.2,
        description: "AP Nasus mid focuses on his Spirit Fire and ultimate for damage. Strengths include strong poke and waveclear. Weaknesses are being vulnerable to all-ins and having a weaker late game compared to AD Nasus."
    },
    {
        Id: 12,
        Name: "Full AP Amumu",
        Lane: "Jungle",
        summonerSpell1: "Smite",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 4.4,
        description: "Full AP Amumu jungle deals massive area-of-effect damage with his abilities. Strengths include strong ganks and high burst damage. Weaknesses are being mana-reliant and squishy."
    },
    {
        Id: 13,
        Name: "Tank Vayne",
        Lane: "Top",
        summonerSpell1: "Flash",
        summonerSpell2: "Teleport",
        build: " ",
        runes: " ",
        rating: 3.7,
        description: "Tank Vayne top relies on her true damage and tankiness to outlast opponents. Strengths include high survivability and true damage. Weaknesses are lower burst damage and being vulnerable to crowd control."
    },
    {
        Id: 14,
        Name: "AD LeBlanc",
        Lane: "Mid",
        summonerSpell1: "Flash",
        summonerSpell2: "Ignite",
        build: " ",
        runes: " ",
        rating: 4.1,
        description: "AD LeBlanc mid focuses on her auto-attacks and on-hit effects. Strengths include high mobility and strong laning phase. Weaknesses are being item-reliant and having lower burst damage."
    },
    {
        Id: 15,
        Name: "AP Garen",
        Lane: "Top",
        summonerSpell1: "Flash",
        summonerSpell2: "Ignite",
        build: " ",
        runes: " ",
        rating: 3.5,
        description: "AP Garen top uses his spin and ultimate for burst damage. Strengths include surprising burst and high sustain. Weaknesses are being easily kited and having a weak early game."
    },
    {
        Id: 16,
        Name: "Tank Teemo",
        Lane: "Top",
        summonerSpell1: "Flash",
        summonerSpell2: "Teleport",
        build: " ",
        runes: " ",
        rating: 3.8,
        description: "Tank Teemo top focuses on survivability and utility. Strengths include high survivability and strong poke. Weaknesses are lower damage output and reliance on shrooms for damage."
    },
    {
        Id: 17,
        Name: "AD Ziggs",
        Lane: "Bot",
        summonerSpell1: "Heal",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 4.0,
        description: "AD Ziggs bot leverages his auto-attacks and on-hit effects. Strengths include strong poke and waveclear. Weaknesses are being squishy and reliant on abilities for damage."
    },
    {
        Id: 18,
        Name: "AP Jhin",
        Lane: "Bot",
        summonerSpell1: "Heal",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 4.3,
        description: "AP Jhin bot focuses on his ability power scaling for burst damage. Strengths include high burst damage and strong poke. Weaknesses are being immobile and reliant on abilities for damage."
    },
    {
        Id: 19,
        Name: "Tank Brand",
        Lane: "Support",
        summonerSpell1: "Ignite",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 4.1,
        description: "Tank Brand support focuses on survivability and crowd control. Strengths include high survivability and strong poke. Weaknesses are lower burst damage and reliance on abilities for damage."
    },
    {
        Id: 20,
        Name: "AP Kog'Maw",
        Lane: "Mid",
        summonerSpell1: "Flash",
        summonerSpell2: "Ignite",
        build: " ",
        runes: " ",
        rating: 4.5,
        description: "AP Kog'Maw mid leverages his ability power scaling for massive poke damage. Strengths include high burst damage and strong poke. Weaknesses are being immobile and squishy."
    },
    {
        Id: 21,
        Name: "AD Yuumi",
        Lane: "Bot",
        summonerSpell1: "Heal",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 3.6,
        description: "AD Yuumi bot leverages her attack speed and on-hit effects. Strengths include high poke and sustain. Weaknesses are being extremely squishy and reliant on abilities for damage."
    },
    {
        Id: 22,
        Name: "Tank Master Yi",
        Lane: "Top",
        summonerSpell1: "Flash",
        summonerSpell2: "Ignite",
        build: " ",
        runes: " ",
        rating: 3.9,
        description: "Tank Master Yi top focuses on survivability and sustained damage. Strengths include high survivability and true damage. Weaknesses are being vulnerable to crowd control and item-reliant."
    },
    {
        Id: 23,
        Name: "AP Miss Fortune",
        Lane: "Bot",
        summonerSpell1: "Heal",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 4.2,
        description: "AP Miss Fortune bot focuses on her ability power scaling for poke and burst damage. Strengths include high poke and burst damage. Weaknesses are being immobile and squishy."
    },
    {
        Id: 24,
        Name: "AD Sona",
        Lane: "Bot",
        summonerSpell1: "Heal",
        summonerSpell2: "Flash",
        build: " ",
        runes: " ",
        rating: 3.7,
        description: "AD Sona bot leverages her auto-attacks and on-hit effects. Strengths include high poke and sustain. Weaknesses are being extremely squishy and reliant on abilities for damage."
    },
    {
        Id: 25,
        Name: "Tank Fizz",
        Lane: "Top",
        summonerSpell1: "Flash",
        summonerSpell2: "Ignite",
        build: " ",
        runes: " ",
        rating: 3.8,
        description: "Tank Fizz top focuses on survivability and utility. Strengths include high survivability and strong engage. Weaknesses are lower damage output and being vulnerable to poke."
    },
    {
        "Id": 52,
        "Name": "AD Lulu",
        "Lane": "Bot",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": " ",
        "runes": " ",
        "rating": 3.8,
        "description": "AD Lulu builds attack damage and attack speed items to enhance her basic attacks. Relies on her utility and polymorph ability to kite enemies and protect allies."
    },
    {
        "Id": 53,
        "Name": "Bruiser Veigar",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": " ",
        "runes": " ",
        "rating": 4.0,
        "description": "Bruiser Veigar builds a mix of AP and tanky items to survive in the top lane while still dealing significant burst damage with his abilities. Focuses on stacking his Q to increase AP."
    },
    {
        "Id": 54,
        "Name": "On-Hit Bard",
        "Lane": "Bot",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": " ",
        "runes": " ",
        "rating": 3.5,
        "description": "On-Hit Bard builds attack speed and on-hit items to enhance his basic attacks. Utilizes his mobility to roam the map and provide utility while still dealing damage."
    },
    {
        "Id": 55,
        "Name": "Tank Karthus",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": " ",
        "runes": " ",
        "rating": 4.1,
        "description": "Tank Karthus focuses on building tanky items to become a durable frontline presence. Relies on his ultimate to deal damage in teamfights while soaking up damage for the team."
    },
    {
        "Id": 56,
        "Name": "AD Nami",
        "Lane": "Bot",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": " ",
        "runes": " ",
        "rating": 3.6,
        "description": "AD Nami builds attack damage and attack speed items to enhance her basic attacks. Relies on her crowd control abilities to peel for allies while dealing sustained damage."
    },
    {
        "Id": 57,
        "Name": "AP Pantheon",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": " ",
        "runes": " ",
        "rating": 3.9,
        "description": "AP Pantheon builds ability power and cooldown reduction items to enhance his burst damage with his abilities. Focuses on roaming and ganking to snowball the game."
    },
    {
        "Id": 58,
        "Name": "Bruiser Lulu",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": " ",
        "runes": " ",
        "rating": 4.0,
        "description": "Bruiser Lulu builds a mix of AP and tanky items to survive in the top lane while still providing utility with her abilities. Utilizes her polymorph and ultimate to disrupt enemy carries."
    },
    {
        "Id": 59,
        "Name": "AP Shaco Support",
        "Lane": "Bot",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": " ",
        "runes": " ",
        "rating": 4.2,
        "description": "AP Shaco Support focuses on building ability power and cooldown reduction items to enhance his burst damage and utility. Relies on deception and box traps to control the lane."
    },
    {
        "Id": 60,
        "Name": "Tank Teemo",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": " ",
        "runes": " ",
        "rating": 4.3,
        "description": "Tank Teemo builds tanky items to become a durable frontline presence while still dealing damage with his poison. Utilizes his blind and shrooms for crowd control and zoning."
    },
    {
        "Id": 61,
        "Name": "AP Alistar",
        "Lane": "Mid",
        "summonerSpell1": "Flash",
        "summonerSpell2": "Ignite",
        "build": " ",
        "runes": " ",
        "rating": 4.0,
        "description": "AP Alistar builds ability power and cooldown reduction items to enhance his burst damage and crowd control. Focuses on roaming and engaging fights with his ultimate."
    },
    {
        "Id": 62,
        "Name": "AD Blitzcrank",
        "Lane": "Bot",
        "summonerSpell1": "Heal",
        "summonerSpell2": "Flash",
        "build": " ",
        "runes": " ",
        "rating": 3.7,
        "description": "AD Blitzcrank builds attack damage and cooldown reduction items to enhance his basic attacks and abilities. Relies on hooking enemies and bursting them down with his combo."
    },
    {
        "Id": 63,
        "Name": "Bruiser Brand",
        "Lane": "Top",
        "summonerSpell1": "Teleport",
        "summonerSpell2": "Flash",
        "build": " ",
        "runes": " ",
        "rating": 3.9,
        "description": "Bruiser Brand builds a mix of AP and tanky items to survive in the top lane while still dealing damage with his abilities. Utilizes his passive to apply % health damage."
    }

]
